name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Build the site
      run: |
        echo "Injecting environment variables"
        sed -i 's|__AUTH_USERNAME__|'${{ secrets.AUTH_USERNAME }}'|g' index.html
        sed -i 's|__AUTH_PASSWORD__|'${{ secrets.AUTH_PASSWORD }}'|g' index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}  # GitHub token is automatically available
        publish_dir: ./  # Adjust to your build output directory
        
    # - name: Invalidate GitHub Pages cache
    #   uses: actions/cache@v3
    #   with:
    #     path: ./public  # Adjust this path to your actual build output
    #     key: ${{ runner.os }}-site-cache
    #     restore-keys: |
    #       ${{ runner.os }}-site-cache
